version: "3.7"

services:
    
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        build: ./postgres
        expose:
         - "5432"
        volumes:
         - /data/Joscha/tables/postgres:/vol_tables

    mdb1:
        image: mdb_crime
        container_name: mdb_crime
        build:
            context: ./mariadb
            dockerfile: DockerfileCrime
        restart: always
        expose:
         - "3306"
        environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=mdb
        - MYSQL_USER=mariadb
        - MYSQL_PASSWORD=123456
        

    mdb2:
        image: mdb_criminals
        container_name: mdb_criminals
        build:
            context: ./mariadb
            dockerfile: DockerfileCriminal
        restart: always
        expose:
         - "3306"
        environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=mdb
        - MYSQL_USER=mariadb
        - MYSQL_PASSWORD=123456


    ne1:
        image: node_executor
        container_name: ne1
        build: ./nodeExecutor
        restart: always
        ports:
            - '1600:1600'
        environment:
          CLUSTER_PORT: 1600
          CLUSTER_IP: ne1
          SEED_PORT_1600_TCP_ADDR: ne1
          JDBC_URL: "jdbc:postgresql://postgres:5432/db1"
          JDBC_USER: odbc_user
          JDBC_PW: password
          EEHOSTNAME: postgres
          ENGINE: postgres

    ne2:
        image: node_executor
        container_name: ne2
        build: ./nodeExecutor
        restart: always
        ports:
            - '1601:1601'
        environment:
          CLUSTER_PORT: 1601
          CLUSTER_IP: ne2
          SEED_PORT_1600_TCP_ADDR: ne1
          JDBC_URL: "jdbc:mariadb://mdb_crime:3306/mdb"
          JDBC_USER: mariadb
          JDBC_PW: 123456
          EEHOSTNAME: mdb_crime
          ENGINE: mariadb

    ne3:
        image: node_executor
        container_name: ne3
        build: ./nodeExecutor
        restart: always
        ports:
            - '1602:1602'
        environment:
          CLUSTER_PORT: 1602
          CLUSTER_IP: ne3
          SEED_PORT_1600_TCP_ADDR: ne1
          JDBC_URL: "jdbc:mariadb://mdb_criminals:3306/mdb"
          JDBC_USER: mariadb
          JDBC_PW: 123456
          EEHOSTNAME: mdb_criminals
          ENGINE: mariadb
